# Change these first
owner: modelrailroader
repo: status-iPad-FAQ

sites:
  - name: iPad-FAQ
    url: https://www.melle-gymnasium.de/ipad-faq
  - name: Google
    url: https://www.google.com
  - name: NextCloud
    url: https://cloud.jans-allerlei.de

status-website:
  robotsText: "User-agent: * \n Disallow: /"
  #baseUrl: /status-iPad-FAQ
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.jans-allerlei.de
  logoUrl: https://raw.githubusercontent.com/modelrailroader/status-iPad-FAQ/master/pics/Logo.png
  name: Upptime
  introTitle: "**Gymnasium Melle** Status Website"
  introMessage: "Status of webservices of Gymnasium Melle"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Gymnasium Melle
      href: https://www.melle-gymnasium.de

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
